[package]
name = "pornos"
version = "0.1.0"
edition = "2021"
authors = ["TornaxO7 <tornax07@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
volatile = "0.4.5"
spin = "0.9.4"
lazy_static = { version = "1.4.0", features = ["spin_no_std"]}
stivale-boot = "0.3.1"
x86_64 = "0.14.10"
uart_16550 = "0.2.18"
