[build]
target = "./x86_64.json"

[unstable]
# build-std = ["core", "compiler_builtins", "alloc"]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64]
runner = ".cargo/runner.sh"
